require_relative 'controllers/application_controller'
require_relative 'controllers/book_controller'
require_relative 'controllers/user_controller'
require_relative 'controllers/session_controller'

use BookController
use UserController
use SessionController
run ApplicationController