source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sequel', '~> 5.0'
gem 'sqlite3', '~> 1.6'
gem 'puma', '~> 6.0'
gem 'rack', '~> 2.2'
gem 'rackup', '~> 1.0'
gem "jwt", "~> 3.1"

# AWS S3 Integration
gem 'aws-sdk-s3', '~> 1.0'
gem 'marcel', '~> 1.0'          # Para detectar MIME types
gem 'dotenv', '~> 2.8'          # Para variables de entorno
gem 'securerandom'               # Para generar nombres únicos
gem 'nokogiri', '~> 1.15'       # Para AWS SDK (XML parsing)

group :development do
  gem 'rerun'
end

