source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sequel', '~> 5.0'
gem 'sqlite3', '~> 1.6'
gem 'puma', '~> 6.0'
gem 'rack', '~> 2.2'
gem 'rackup', '~> 1.0'
gem "jwt", "~> 3.1"
group :development do
  gem 'rerun'
end

